#!/bin/bash

# Up -- Debian/Ubuntu Update Tool (Version 1.2)
# Advanced command to fully update system: "up" Adding the option "--clean" will
# remove orphaned packages and auto-clean the apt cache. (January, 2018)
# By Joe Collins www.ezeelinux.com (GNU/General Public License version 2.0)

# Set BASH to quit script and exit on errors:

set -e

# Functions:

update() {

echo "Starting full system update..."
sudo apt update
sudo apt dist-upgrade -yy

}

clean() {

echo "Cleaning up..."
sudo apt autoremove -yy
sudo apt autoclean

}

leave() {

echo "--------------------"
echo "- Update Complete! -"
echo "--------------------"
exit

}

up-help() {

cat << _EOF_

 Up is a tool that automates the update procedure for Debian and Ubuntu based
 Linux systems.

 Commands:
    up = full system update.

    Running "up" with no options will update the apt cache and then perform a
    full distribution update automatically.

    up --clean = full system update with cleanup.

    Adding the "--clean" option will invoke the apt commands to search for and
    remove locally cached packages that are no longer in the repositories and
    remove orphaned packages that are no longer needed by programs.

    up --help = shows this help page.

 By Joe Collins www.ezeelinux.com (GNU/General Public License version 2.0)

_EOF_

}

up-error(){

    echo "Up Error: Invalid argument. Try 'up --help' for more info." >&2

}

# Execution.

# Tell 'em who we are...

echo "Up -- Debian/Ubuntu Update Tool (Version 1.2)"

# Check for arguments

if  [ -n "$1"  ]; then
    case $1 in
        --clean) cleanset=1;;
        --help) up-help; exit;;
        *) up-error; exit 1;;
    esac
fi

# Run the script

update
if [ "$cleanset" == "1" ]; then
    clean
fi
leave
